extends:
  - next/core-web-vitals
  - prettier

overrides:
  - files:
      - tests/**
    plugins:
      - jest
    extends:
      - plugin:jest/recommended
      - plugin:jest/style

rules:
  react/no-unknown-property:
    - error
    - ignore:
        - css
  react/prop-types: off
